#!/bin/sh
# eric.mourgaya@arkea.com
# Apache Licence
### BEGIN INIT INFO
# Default-Start:     3
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

RETVAL=0
PYTHONBIN=`which python`
case "$1" in
  start)
    echo "Starting sysprob daemon"
    $PYTHONBIN /opt/inkscope/bin/sysprobe.py start
    RETVAL=$?
    ;;
  stop)
    echo "Stopping  sysprob daemon" 
    $PYTHONBIN /opt/inkscope/bin/sysprobe.py stop
    ;;
  restart)
    echo "Restarting  sysprob daemon" 
    $PYTHONBIN /opt/inkscope/bin/sysprobe.py restart
    ;;
  status)
    echo "Status  sysprob daemon" 
    $PYTHONBIN /opt/inkscope/bin/sysprobe.py status
    ;;
  *)
    echo "Usage: /etc/init.d/sysprob {start|stop|status|restart}"
    exit 1
    ;;
esac

exit 0

