#!/usr/bin/python
#@author eric Mourgaya
# check  ceph health
# import  the libmonjuice  from /opt/inkscope/lib
import os
import sys
LIBREP="/opt/inkscope/lib/"
LIBPATH=os.path.dirname(LIBREP)
if LIBPATH not in sys.path:
    sys.path.append(LIBPATH)
from libmongojuice import *
import sys

res,msg=sysprobeis_uptodate(600000)
if  res == 0:
    print "process sysprobe is up to date ok ",msg
elif res == 1:
    print "warning sysprobe "+ "check it on "+ msg
else:
    print "warning sysprobe "+ "check it on "+ msg

sys.exit(res)

