#!/usr/bin/python
#@author eric Mourgaya
# check  ceph health
# import  the libmonjuice  from /opt/inkscope/lib
import os
import sys
LIBREP="/opt/inkscope/lib/"
LIBPATH=os.path.dirname(LIBREP)
if LIBPATH not in sys.path:
    sys.path.append(LIBPATH)
from libmongojuice import *
import sys

res=isallosd_up()

if  res == 0:
    print "all osd are  okdk"
elif res == 1:
    print "warning  something wrong check ceph -s to see more "
else:
    print "alert: an osd is failed check it with ceph osd tree cmd!"
sys.exit(res)

