#!/usr/bin/python
#@author eric Mourgaya
# check  ceph health
from libmongojuice import *
import sys

res=isallosd_up()

if  res == 0:
    print "osd health ok"
elif res == 1:
    print "warning  something  wrong : try ceph osd tree "
else:
    print "alert:  something really wrong with osds try: ceph osd tree!"
sys.exit(res)

