#!/usr/bin/python
#@author eric Mourgaya
# check  ceph health
# import  the libmonjuice  from /opt/inkscope/lib
import os
import sys
LIBREP="/opt/inkscope/lib/"
LIBPATH=os.path.dirname(LIBREP)
if LIBPATH not in sys.path:
    sys.path.append(LIBPATH)
from libmongojuice import *
import sys

res,msg=mon_df()

if  res == 0:
    print "ceph  mon space is not full ok"
elif res == 1:
    print "warning  something  wrong ceph mon space is near full: see "+msg
else:
    print "alert  something  wrong ceph mon space is full: see "+msg
sys.exit(res)

