#!/usr/bin/python
#@author eric Mourgaya
# check  ceph health
from libmongojuice import *
import sys

res=cephprobeis_uptodate(10000)

if  res == 0:
    print "probe ok"
elif res == 1:
    print "warning  something  wrong with cephprobe "
else:
    print "alert:  something really wong with cephprobe!"
sys.exit(res)

